/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyHomework;
import java.util.ArrayList;
import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean search(ArrayList<Integer> array1,ArrayList<Integer> array2,int first,int second){

        if(array1 == null || array2 == null)
            return false;
        int count=0;
        for(int elt : array1){
            if(elt == first)
                count++;
        }
        int count2=0;
        for(int elt : array2){
            if(elt == first)
                count2++;
        }

        if(count == count2 && count == second)
            return true;
            
            return false;

    }

}
