/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyHomework;
import java.util.ArrayList;
import java.util.Arrays;
import static spark.Spark.get;
  import static spark.Spark.port;
  import static spark.Spark.post;
  
  import java.util.HashMap;
  import java.util.Map;
  import spark.ModelAndView;
  import spark.template.mustache.MustacheTemplateEngine;




public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        port(getHerokuAssignedPort());

        get("/", (req, res) -> "Hello, World");

        post("/compute", (req, res) -> {
          //System.out.println(req.queryParams("input1"));
          //System.out.println(req.queryParams("input2"));

          String input1 = req.queryParams("input1");
          java.util.Scanner sc1 = new java.util.Scanner(input1);
          sc1.useDelimiter("[;\r\n]+");
          java.util.ArrayList<Integer> inputList = new java.util.ArrayList<>();
          while (sc1.hasNext())
          {
            int value = Integer.parseInt(sc1.next().replaceAll("\\s",""));
            inputList.add(value);
          }
          sc1.close();
          System.out.println(inputList);

          String input2 = req.queryParams("input2");
          java.util.Scanner sc2 = new java.util.Scanner(input2);
          sc1.useDelimiter("[;\r\n]+");
          java.util.ArrayList<Integer> inputList2 = new java.util.ArrayList<>();
          while (sc2.hasNext())
          {
            int value = Integer.parseInt(sc2.next().replaceAll("\\s",""));
            inputList2.add(value);
          }
          sc2.close();
          System.out.println(inputList2);


          String input3 = req.queryParams("input3");
          java.util.Scanner sc3 = new java.util.Scanner(input3);
          sc3.useDelimiter("[;\r\n]+");
          int input3AsInt = Integer.parseInt(sc3.next().replaceAll("\\s", ""));
          int input4AsInt = Integer.parseInt(sc3.next().replaceAll("\\s", ""));
          System.out.println(input3AsInt +" "+ input4AsInt);
          boolean result = App.search(inputList, inputList2, input3AsInt,input4AsInt);

          Map<String, Boolean> map = new HashMap<String, Boolean>();
          map.put("result", result);
          return new ModelAndView(map, "compute.mustache");
        }, new MustacheTemplateEngine());


        get("/compute",
            (rq, rs) -> {
              Map<String, String> map = new HashMap<String, String>();
              map.put("result", "not computed yet!");
              return new ModelAndView(map, "compute.mustache");
            },
            new MustacheTemplateEngine());


    }
    static int getHerokuAssignedPort() {
        ProcessBuilder processBuilder = new ProcessBuilder();
        if (processBuilder.environment().get("PORT") != null) {
            return Integer.parseInt(processBuilder.environment().get("PORT"));
        }
        return 4567; //return default port if heroku-port isn't set (i.e. on localhost)
    }


    public static boolean search(ArrayList<Integer> array1,ArrayList<Integer> array2,int first,int second){

        if(array1 == null || array2 == null)
            return false;
        int count=0;
        for(int elt : array1){
            if(elt == first)
                count++;
        }
        int count2=0;
        for(int elt : array2){
            if(elt == first)
                count2++;
        }

        if(count == count2 && count == second)
            return true;

            return false;

    }

}
