/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyHomework;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.Arrays;


class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test 
    public void testFound(){
        ArrayList<Integer> array1 = new ArrayList<>(Arrays.asList(1, 2, 3, 3, 4));
        ArrayList<Integer> array2 = new ArrayList<>(Arrays.asList(2, 2, 3, 3, 5, 6));
        assertTrue(App.search(array1, array2, 3, 2));
    }
    @Test
    public void testNotFound(){
        ArrayList<Integer> array1 = new ArrayList<>(Arrays.asList(1, 2, 3, 3, 4));
        ArrayList<Integer> array2 = new ArrayList<>(Arrays.asList(2, 2, 3, 3, 5, 6));
        assertFalse(App.search(array1, array2, 2, 2));

    }
    @Test
    public void testEmptyArray() {
      ArrayList<Integer> array = new ArrayList<>();
      ArrayList<Integer> array2 = new ArrayList<>();

      assertFalse(App.search(array,array2,1, 1));
    }

    @Test
    public void testNull() {
      assertFalse(App.search(null, null,1 ,2));
    }

}
